### PR TITLE
specify psutil dependency <= 2.2.1

### PR DESCRIPTION
**Pull request by pfeyz**
@jhamrick's 82cb5555 on the dev branch is a better solution and will clobber this commit, but I'm targeting the master branch in case y'all want to get this released asap so people stop running into issues with the too-new psutil api:

  https://groups.google.com/d/msg/psiturk/XooDMBg33Sg/-yG2UqVH0kYJ
  https://groups.google.com/d/msg/psiturk/bjJXaMqk5O0/4LDHlNO8k7kJ
  https://groups.google.com/d/msg/psiturk/tIDyusjzYIY/KkUSpA4Hj7gJ

### CODE REVIEW

**Comment by gureckis** [comment]
thanks @pfeyz!

**Comment by nirsolomonmate** [comment]
Hi, I am still receiving this error, and I just downloaded this yesterday at approximately 1pm -- any ideas on how I can fix it?

**Comment by gureckis** [comment]
please be sure to install from github
sudo pip install git+git://github.com/NYUCCL/psiTurk.git@master

**Comment by nirsolomonmate** [comment]
hmmm... im still receiving the same error... here is my exact error: 
Traceback (most recent call last):
  File "/usr/local/bin/psiturk", line 11, in <module>
    sys.exit(process())
  File "/usr/local/lib/python2.7/site-packages/psiturk/command_line.py", line 14, in process
    launch_shell()
  File "/usr/local/lib/python2.7/site-packages/psiturk/command_line.py", line 104, in launch_shell
    ps.run(cabinmode=args.cabinmode)
  File "/usr/local/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 1780, in run
    config.getboolean('Shell Parameters', 'launch_in_sandbox_mode'))
  File "/usr/local/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 507, in __init__
    PsiturkShell.__init__(self, config, server)
  File "/usr/local/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 119, in __init__
    self.color_prompt()
  File "/usr/local/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 571, in color_prompt
    server_status = self.server.is_server_running()
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment_server_controller.py", line 144, in is_server_running
    psiturk_exp_ports = [process[0].laddr[1] for process in [psutil.Process(int(pid)).get_connections() for pid in output]]
AttributeError: 'Process' object has no attribute 'get_connections'

**Comment by pfeyz** [comment]
I just tried to replicate your issue but failed. I ran it in a virtual environment, so I'm not prefixing my pip commands with sudo.

1. Install the current release of psiturk
    ```
    $ pip install psiturk
    ...
    Successfully installed Flask-0.10.1 Jinja2-2.8 MarkupSafe-0.23 SQLAlchemy-1.0.8 Werkzeug-0.10.4 argparse-1.3.0 boto-2.38.0 cmd2-0.6.8 docopt-0.6.2 fake-factory-0.5.2 fuzzywuzzy-0.6.0 gitdb-0.6.4 gitpython-1.0.1 gnureadline-6.3.3 gunicorn-19.3.0 itsdangerous-0.24 psiturk-2.1.2 psutil-3.1.1 pyparsing-2.0.3 requests-2.7.0 setproctitle-1.1.9 sh-1.11 smmap-0.9.0 ua-parser-0.3.6 user-agents-0.3.2
```

2. Try to launch the server, observe AttributeError.
    ```
    $ psiturk
    ...
    [psiTurk server:off mode:sdbx #HITs:0]$ server on
    ....
    AttributeError: 'Process' object has no attribute 'get_connections'
    [psiTurk server:off mode:sdbx #HITs:0]$ C-c
```

3. Install directly from master branch
    ```
    $ pip install git+git://github.com/NYUCCL/psiTurk.git@master
    Requirement already satisfied (use --upgrade to upgrade): argparse in /home/paul/.virtualenvs/test-fix/lib/python2.7/site-packa
ges (from PsiTurk==2.1.2)

    Requirement already satisfied (use --upgrade to upgrade): Flask in /home/paul/.virtualenvs/test-fix/lib/python2.7/site-packages
    ...
    Installing collected packages: psutil
      Found existing installation: psutil 3.1.1
        Uninstalling psutil-3.1.1:
          Successfully uninstalled psutil-3.1.1
    Successfully installed psutil-2.2.1
     (from PsiTurk==2.1.2)
```

4. Successfully launch psiturk server.
    ```
    $ psiturk
    [psiTurk server:off mode:sdbx #HITs:0]$ server on
    Experiment server launching...
    Now serving on http://localhost:22362
    [psiTurk server:on mode:sdbx #HITs:0]$
```

At what point does this deviate from what happens for you?

**Comment by nirsolomonmate** [comment]
At step 3. 
When I try to install directly from master branch I get the following error:

Command "git clone -q git://github.com/NYUCCL/psiTurk.git /var/folders/14/pr4tftf91vbdsl77mnc7xs900000gn/T/pip-8hPZ6T-build" failed with error code 128 in None

I am assuming its a python error because I have an error with "None" and have checked that I am using the correct python version 2.7.10... any ideas? Thanks for your help! I appreciate it.

**Comment by pfeyz** [comment]
maybe try cloning over http?

    $ pip install git+http://github.com/NYUCCL/psiTurk.git@master

**Comment by yuchuochuo1023** [comment]
There is a psutil-1.2.1 in my computer (I tried to upgrade it to version 2.2.1 manually, but it was uninstalled by Psiturk and reinstalled version 1.2.1). I downloaded psiturk successfully already. However, I met an AttributeError  when I ran the command 'psiturk-setup-example'. It seems that this problem is caused by psutil. Could anyone try to help me? The following is the error message. 

Further detail (if help): I tried to run command '$pip install psiturk' and '$pip install git+git://github.com/NYUCCL/psiTurk.git@master'. Both of them can install psiturk successfully. But I met the same error when I run '$psiturk-setup-example'.

qiandeMBP:~ qian$ psiturk-setup-example
/Users/qian/anaconda/lib/python2.7/site-packages/psutil/_psosx.py:34: RuntimeWarning: couldn't determine platform's NUM_CPUS
  warnings.warn("couldn't determine platform's NUM_CPUS", RuntimeWarning)
/Users/qian/anaconda/lib/python2.7/site-packages/psutil/_psosx.py:39: RuntimeWarning: couldn't determine platform's BOOT_TIME
  warnings.warn("couldn't determine platform's BOOT_TIME", RuntimeWarning)
/Users/qian/anaconda/lib/python2.7/site-packages/psutil/_psosx.py:44: RuntimeWarning: couldn't determine platform's TOTAL_PHYMEM
  warnings.warn("couldn't determine platform's TOTAL_PHYMEM", RuntimeWarning)
Traceback (most recent call last):
  File "/Users/qian/anaconda/bin/psiturk-setup-example", line 9, in <module>
    load_entry_point('PsiTurk==2.1.6', 'console_scripts', 'psiturk-setup-example')()
  File "/Users/qian/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 547, in load_entry_point
  File "/Users/qian/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2719, in load_entry_point
  File "/Users/qian/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2379, in load
  File "/Users/qian/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2385, in resolve
  File "/Users/qian/anaconda/lib/python2.7/site-packages/psiturk/command_line.py", line 7, in <module>
    from psiturk.psiturk_org_services import ExperimentExchangeServices
  File "/Users/qian/anaconda/lib/python2.7/site-packages/psiturk/psiturk_org_services.py", line 15, in <module>
    import psutil
  File "/Users/qian/anaconda/lib/python2.7/site-packages/psutil/__init__.py", line 145, in <module>
    import psutil._psosx as _psplatform
  File "/Users/qian/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 75, in <module>
    get_system_boot_time = _psutil_osx.get_system_boot_time
AttributeError: 'module' object has no attribute 'get_system_boot_time'

**Comment by deargle** [comment]
Quick suggestions: try without anaconda (we don't support that), use a
virtualenv

**Comment by deargle** [comment]
> There is a psutil-1.2.1 in my computer (I tried to upgrade it to version 2.2.1 manually, but it was uninstalled by Psiturk and reinstalled version 1.2.1)

I wonder why it would do that?

Ah. Because requirements.txt specifies psutil==1.2.1, and this PR had only touched `setup.py` which was overwritten by a later PR that reads from `requirements.txt`

How about we just change requirements.txt to be `psutil==2.2.1`? @pfeyz is there a reason why it was specifically `<=2.2.1` before?

I think this will fix everyone's recent anaconda problems, too.

**Pull request merged**
