### PR TITLE
Fix SSTI vulnerability in ad and consent pages

### PR DESCRIPTION
**Pull request by BlaiseRitchie**
Fixed an issue where users could pass arbitrary Python code to be executed on the server to the mode HTTP arg

More information about this type of vulnerability: https://secure-cookie.io/attacks/ssti/

### CODE REVIEW

**Comment by BlaiseRitchie** [comment]
Here's an example of reading a server-side file from /etc using the default psiturk-setup-example project:
SSTI vulnerability example

**Comment by deargle** [comment]
🎉 🎉 🎉 awesome, how did you find this?

**Comment by BlaiseRitchie** [comment]
> 🎉 🎉 🎉 awesome, how did you find this?

A whitehat security researcher reported it to us

**Comment by deargle** [comment]
I'm considering just stripping out all of the `insert_mode` calls etc. I think that was for maintaining compatibility between psiturk 1 and 2 -- I don't think any psiturk 1 template would work anymore anyway.

**Comment by deargle** [comment]
But I'll merge this for now.

**Pull request merged**
