### PR TITLE
Creating a document describing how to set up and run psiTurk on Heroku

### PR DESCRIPTION
**Pull request by Speldosa**
We've discussed creating docs for setting up psiTurk on Heroku in issue
#306. I've tried following and rewriting some instructions on how to do
this referenced there.

Some of the instructions I couldn't execute without changing the API
calls (most notably, you have to append `--app <your app name>` to almost all commands), and right now, the whole process fails when trying to launch the
app.

I'm creating a pull request at this stage to hopefully get some
feedback on how to proceed.

This is the error I'm getting after running `git push heroku master`:

```
Counting objects: 51, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (47/47), done.
Writing objects: 100% (51/51), 219.13 KiB | 6.09 MiB/s, done.
Total 51 (delta 4), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote:  !     The latest version of Python 2 is python-2.7.14 (you are using python-2.7.13, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-2.7.14).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing python-2.7.13
remote: -----> Installing pip
remote: -----> Installing requirements with pip
remote:        Collecting PsiTurk (from -r /tmp/build_9b3bcd85ac3f00ba1449d31fc49258df/requirements.txt (line 1))
remote:          Downloading PsiTurk-2.2.3.tar.gz (3.4MB)
remote:        Collecting psycopg2==2.6.2 (from -r /tmp/build_9b3bcd85ac3f00ba1449d31fc49258df/requirements.txt (line 2))
remote:          Downloading psycopg2-2.6.2.tar.gz (376kB)
remote:            Complete output from command python setup.py egg_info:
remote:            running egg_info
remote:            creating pip-egg-info/psycopg2.egg-info
remote:            writing pip-egg-info/psycopg2.egg-info/PKG-INFO
remote:            writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
remote:            writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
remote:            writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
remote:            Error: could not determine PostgreSQL version from '10.3'
remote:            
remote:            ----------------------------------------
remote:        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Azskfi/psycopg2/
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to dry-spire-54490.
remote: 
To https://git.heroku.com/dry-spire-54490.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/dry-spire-54490.git'
```

### CODE REVIEW

**Comment by deargle** [comment]
Use the `requirements.txt` from the master branch (https://github.com/NYUCCL/psiTurk/blob/master/psiturk/example/requirements.txt), which uses `psycopg2==2.7.1` instead of 2.6.3, and try again.

Also, bump `runtime.txt` to `python-2.7.14` to avoid that warning message.

And you should _not_ have to specify `--app` if you run the commands from a directory that has a .git/config that has an entry for `heroku`. `--app` is necessary if you want to run a command against an app from any arbitrary directory.

**Comment by Speldosa** [comment]
Updating `requirements.txt` and `runtime.txt` worked when it comes to launching the app on Heroku. I guess this won't have to be part of the instructions though since I guess these docs can be launched whenever psiturk is updated.

Regarding the --app thing: Is there a command in your original instructions that should set up such a connection (the `git init` command is issued before the heroku cli even is used)? Or should I add something new to the docs?

**Comment by deargle** [comment]
> Regarding the --app thing: Is there a command in your original instructions that should set up such a connection (the git init command is issued before the heroku cli even is used)? Or should I add something new to the docs?

Yes, the `heroku create` command takes care of that. Again, one of the things that `heroku create` does is adds an entry to your .git/config file for a remote called "heroku" pointing to whatever domain name assigned to you during the earlier `hit create` process.

**Comment by deargle** [comment]
PS, it is likely that you ran `heroku create` from a directory other than where your experiment resides. It matters what your cwd is when you run the command. _That_ directory will be initialized as a git repo and given the `heroku` remote. You can just copy the relevant section from .git/config from wherever that was initialized into where it should have gone (your project dir).

**Comment by Speldosa** [comment]
I see. Your hypothesis is probably true :) I've tried it now, and it works as you describe. I'll update the documentation to reflect this.

One last thing (hopefully :P): I guess you can't run the `download_datafiles` command on the Heroku app and then download the csv files, but that you rather have to download the database itself (you can for example do this manually from the Heroku website) and then run the `download_datafiles` command locally.

**Comment by deargle** [comment]
Actually, if the download_datafiles command worked at all, you should be
able to run it from anywhere. I think it's defunct though. I use the
general approach shown in the script here:
http://psiturk.readthedocs.io/en/latest/retrieving.html

**Comment by Speldosa** [comment]
Ping issue #254.

**Comment by Speldosa** [comment]
I consider this pull request done now.

**Comment by Speldosa** [comment]
Well, `download_datafiles` seems to *work*, at least for my purposes.

**Comment by deargle** [comment]
Thanks for your work on these docs. I made a few edits to what you wrote, take a look to see some tips and tricks and clarifications, some of which may help your heroku flow.

And good to hear about `download_datafiles`. I think I was thinking about the `server log` command. That is definitely defunct.

**Pull request merged**
