### PR TITLE
Refactor server shutdown

### PR DESCRIPTION
**Pull request by jacob-lee**
- removes the http request and route to get ppid of server
- uses shutil to shutdown the process tree
- refactors the edge case for when ^C is entered in the psiturk-shell

### CODE REVIEW

**Comment by deargle** [comment]
Hmm wait I'm confused, why have the flask server handle the ctrl+c exit? I sometimes run the flask debug server _without_ gunicorn, for debugging.

**Comment by jacob-lee** [comment]
It just sets a signal handler in experiment.py that catches SIGINT and
calls sys exit. I'm not hooking into gunicorn afaik. I probably should have
separated this change from the rest of the commit, but having it report
that there was a ctrl-c whenever there was a shutdown seemed wrong. It was
doing that because I use SIGTERM to shutdown, which allows the on exit hook
to run. But I couldn't figure a way to check how the exit was triggered in
the exit hook.

**Comment by deargle** [comment]
Oh! Thanks, that makes sense.

I'll play with this after I finish the doc overhaul I'm doing, I'm a laser rn.

**Comment by deargle** [comment]
Can we switch this to use logger instead of print statements?

**Comment by jacob-lee** [comment]
I like switching to a logger because we can use a streamHandler for the CLI and shell/script, but add other handlers like an HTTP handler in case we want to push logs to web app interface.

I accidentally pushed the last commit to github. Please disregard any errors that show up.

**Comment by jacob-lee** [comment]
Any more issues that need to be addressed before pulling?

**Comment by deargle** [comment]
I'm going to test that heroku etc still works for me before merging this

**Comment by deargle** [comment]
Thanks for this! Looks much cleaner.

**Comment by deargle** [comment]
I just pushed 99de42803261ea850cd116fba20ac9d291928083 moving the sigint handling out of experiment.py and into experiment_server.py. I remembered my use case -- to run the experiment.py using `flask run`, to get the benefits of live code reloading, no need to restart psiturk server. flask server was complaining about the signal binding being in that file, since experiment.py gets forked a lot by it, and signal binding should only be in the main thread.

**Pull request merged**
