### PR TITLE
Test suite and huge refactor in preparation for python3 and web interface

### PR DESCRIPTION
**Pull request by deargle**
This branch has a test suite for the services wrapper. It mocks out all calls to boto so that we're not actually hitting the mturk servers for each test. Check the changelog.md file for more info, but all print statements have been stripped out of the wrapper and isolated to the shell file.

It would be good if a few people could test this to make sure that it doesn't break anything monstrous. If it's stable, we can move on to more feature integration -- like easier heroku setup perhaps, and a web management interface. I'm going to start on python3 with this branch.

### CODE REVIEW

**Comment by deargle** [comment]
@fredcallaway @jacoblee could you also help with testing this out?

**Comment by fredcallaway** [comment]
🎉🎉🎉

I'll try posting a HIT to the sandbox using this version!

**Comment by fredcallaway** [comment]
I get an error: 
```
  Sorry, there was an error creating hit and registering ad.
Error during hit createion.
```
(note also the typo, "createion")

I confirmed that I can still post hits with the current master branch (v2.3.0)

**Comment by fredcallaway** [comment]
here's my config: https://gist.github.com/fredcallaway/b027c6aeda8c17aa6eebc2487826cfa2

**Comment by deargle** [comment]
Could be related to the broken psiturk ad server. I'll add more error reporting there and ping back.

Meanwhile can you try switching your config to use heroku for the ad?

```
use_psiturk_ad_server = false
ad_location = https://cocosci-blockworld.herokuapp.com/pub
```

**Comment by fredcallaway** [comment]
@deargle Now I can create the HIT, but when I view it through mturk I get

> Sorry, there was an unexpected error in our processing of your HIT.
> 
> If you would like to receive partial compensation or feel you have reached this page in error, please email support@psiturk.org and send the following information:
> 
> Error: #1016
> HITID: #[u'39HYCOOPKOLY9W3IMKMPSCO0WM7MDS']
> WorkerId: #[u'A1T3UYMHKPS4MF']

However, the Ad URL works: https://cocosci-blockworld.herokuapp.com/pub?mode=sandbox&assignmentId=debug9TEZFS&hitId=debugOAS764&workerId=debugDK05P7

**Comment by fredcallaway** [comment]
Now I'm getting the `api_server_not_reachable` (1015) error when I click the start experiment button on the ad.

**Comment by deargle** [comment]
Hmm sounds like it's still using the ad server. In hindsight i didn't add
any tests that use the ad server, knowing it was broken, and not wanting to
test against it. I'll poke around a bit and try to figure out why yours is
breaking and still using the ad server-- maybe the first hit one you
created before config change actually posted, and that's the one that is
throwing that error? Try deleting all?

**Comment by deargle** [comment]
I forgot that there's also a few other heroku related things you would need
to do to before it would work there. Docs page is kind of good at
summarizing.

**Comment by fredcallaway** [comment]
> I forgot that there's also a few other heroku related things you would need to do to before it would work there. Docs page is kind of good at summarizing.

Do you mean https://psiturk.readthedocs.io/en/latest/heroku.html? I've done all that already. To be clear, I ran this experiment on heroku using the psiturk ad server in January.

**Comment by fredcallaway** [comment]
OK I figured out the problem. I have not been pushing config.txt to heroku. At least some changes took effect without committing so I thought it wasn't necessary (and allows me to comfortably put AWS keys there).

I was able to complete a HIT after fixing this.

**Comment by deargle** [comment]
Ohhh snap y'all, we are now tested against and supporting python 2.7, 3.6, and 3.7

**Comment by fredcallaway** [comment]
🎉3⃣🎉3⃣🎉3⃣🎉3⃣🎉3⃣🎉

**Comment by deargle** [comment]
This PR closes #328

**Pull request merged**
